config/routes.rb
Rails.application.routes.draw do

  # patch '/brand/:id/index', to: 'brand#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end

  root to: "items#index"

  resources :items do

    resources :favorites, only: [:create, :destroy, :index]
    resources :comments, only: [:create]

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    # 編集画面でカテゴリーを編集可能にするための記述
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      get 'search'
      get 'detail_search'
      get 'detail_search_result'
    end

    resources :purchase, only: [:index] do
      member do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get '/brand/:id/index', to: 'brand#index', as: 'brand'

  resources :users, only: :show do

    collection do
      get 'logouts', to: 'logouts#index'
      get 'cards', to: 'cards#index'
      get 'user_favorites', to: 'user_favorites#index'
    end
  end

  resources :category, only: :new do
    member do
      get 'parents', to: 'category#parents'
      get 'children', to: 'category#children'
      get 'grand_children', to: 'category#grand_children'
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
  validates :item_id, :user_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favoriteItems = []
    favorites = current_user.favorites.ids
    favorites.each do |f|
      favoriteItem_id = Favorite.find(f).item_id
      @favoriteItem = Item.find(favoriteItem_id)
      @favoriteItems << @favoriteItem
    end
  end

  def create
    @favorite = current_user.favorites.create(item_id: params[:item_id])
    if @favorite.save
      @favoriteCounts = Favorite.where(item_id: params[:item_id])
      respond_to do |format| 
        format.json  
      end 
    else
      redirect_to item_path(@favorite.item.id)
    end
  end

  def destroy
    @favorite = Favorite.find_by(item_id: params[:item_id], user_id: current_user.id)
    @favorite.destroy
    @favoriteCounts = Favorite.where(item_id: params[:item_id])
    respond_to do |format|
      format.json
    end
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.haml
- if user_signed_in?
  - if current_user.already_favorited?(item)
    = button_to 'いいねを取り消す', item_favorite_path(item), {method: :delete, id: "delete-good"}
  - else
    = button_to 'いいね', item_favorites_path(item), {method: :post, id: "good"}
- else
  %p 
    お気に入り数: 
    = item.favorites.count

app/views/favorites/create.js.haml
$('.button_to').html("#{j(render partial: 'favorites/favorite', locals: {item: @item})}");

app/views/favorites/destroy.js.haml
$('.button_to').html("#{j(render partial: 'favorites/favorite', locals: {item: @item})}");

app/views/favorites/index.html.haml
- breadcrumb :favorite

%h1 お気に入り商品一覧ページ
.favoriteItemBox
  .favoriteItemHeader
    お気に入り商品一覧
  %ul.favoriteItemLists
    - @favoriteItems.each do |item|
      = link_to item_path(item.id), method: :get, class:"favoriteItemList" do
        %li.favoreteItemList__box
          .favoriteItemList__box--image
            = image_tag item.images.first.image.url, class: "image"
          .favoriteItemList__box--name
            = item.name
            %br
              = "#{item.price} 円"
              %br
                （税込）

= link_to "ホームへ戻る", root_path