config/routes.rb
Rails.application.routes.draw do

  # patch '/brand/:id/index', to: 'brand#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end

  root to: "items#index"

  resources :items do

    resources :favorites, only: [:create, :destroy, :index]
    resources :comments, only: [:create]

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    # 編集画面でカテゴリーを編集可能にするための記述
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      get 'search'
      get 'detail_search'
      get 'detail_search_result'
    end

    resources :purchase, only: [:index] do
      member do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get '/brand/:id/index', to: 'brand#index', as: 'brand'

  resources :users, only: :show do

    collection do
      get 'logouts', to: 'logouts#index'
      get 'cards', to: 'cards#index'
      get 'user_favorites', to: 'user_favorites#index'
    end
  end

  resources :category, only: :new do
    member do
      get 'parents', to: 'category#parents'
      get 'children', to: 'category#children'
      get 'grand_children', to: 'category#grand_children'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :seller, dependent: :destroy
  has_one :buyer
  has_one :selling_status, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :images, dependent: :destroy
  belongs_to :brand, optional: true
  belongs_to :category
  belongs_to :shipping
  validates :name, :description, :price, :condition, :parent_category_id, :child_category_id, :category, :shipping, :images, presence: true
  validates_associated :images


  enum condition: [ :"新品・未使用", :"未使用に近い", :"目立った傷や汚れなし", :"やや傷や汚れあり", :"傷や汚れあり", :"全体的に状態が悪い" ]
  # mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :shipping
  accepts_nested_attributes_for :brand

  scope :d_search, -> (keyword){where('name LIKE(?)', "%#{keyword}%")}
  scope :previous, -> (item) { where("id < ?", item.id).order('id DESC').first }
  scope :next, -> (item) { where("id > ?", item.id).order('id ASC').first }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_index, except: [:index, :show, :search]
  # ログインユーザー≠出品者のときに、直接URL指定にてedit,update,desytoyへアクセスされた場合も制限するため追記
  before_action :set_item, only: [:show, :edit, :update, :destroy, :ensure_correct_user]
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  before_action :set_ransack


  def index
    @items = Item.all
    @parents = Category.all.order("id ASC").limit(13)
    @apple = Item.all.where(brand_id: 343306)
    @nike = Item.all.where(brand_id: 6739)
    @louisvuitton = Item.all.where(brand_id: 118251)
  end

  def show
    @category = Category.find(@item.parent_category_id)
    @category_child = Category.find(@item.child_category_id)
    @category_grand_child = Category.find(@item.category_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order("created_at DESC")
    @favorite = Favorite.new 
    @images = @item.images
    @image = @images.first
    @previous_item = Item.previous(@item)
    @next_item = Item.next(@item)
  end

  def new
    @item = Item.new
    @item.images.new
  end
  
  def create
    @item = Item.new(item_params)
    # 出品ページからparamsで受け取った入力ワードが既にbrandテーブルにあるか検索
    @brand = Brand.find_by(name: "#{params[:input]}")  
    begin
      ActiveRecord::Base.transaction do   
        if @item.save!
          # ① 既にbrand名が存在すれば@itemデータのbrand_id部分を更新して保存
          if @brand
            @item.update!(brand_id: @brand.id)
          else
            # ②-1 ない場合でかつ入力フォームが空じゃない限りは
            unless "#{params[:input]}".blank?
              # ②-2 まずbrandテーブルに新規で保存
              brand = Brand.new(name: "#{params[:input]}")
              if brand.save!
                # ③-3 上で保存したばかりのbrand_idを@itemで入れて更新、保存
                @item.update!(brand_id: brand.id)
              end
            end
          end
          selling_status = SellingStatus.new(item_id: @item.id, seller_id: params[:user_id], status: "出品中")
          seller = Seller.new(item_id: @item.id, user_id: params[:user_id])
          selling_status.save!
          seller.save!
        end
      end
      redirect_to item_path (@item.id)
    rescue
      flash.now[:alert] = 'エラーが発生しました。'
      render :new
    end
  end
  
  def edit
  end

  def update
    @brand = Brand.find_by(name: "#{params[:input]}")
    begin
      ActiveRecord::Base.transaction do
        @item.update!(item_params)
        if @brand
          @item.update!(brand_id: @brand.id)
        else
          if "#{params[:input]}".blank?
            @item.update!(brand_id: nil)
          else
            brand = Brand.new(name: "#{params[:input]}")
            if brand.save!
              @item.update!(brand_id: brand.id)
            end
          end
        end
      end
      redirect_to root_path
    rescue
      flash.now[:alert] = 'エラーが発生しました。'
      render :edit
    end
  end

  def search
    @search_item = Item.ransack(params[:q])
    @items = @search_item.result.page(params[:page])
    @grandchild_category = Category.where('ancestry LIKE(?)',"%/%")
    @child_category = Category.where.not('ancestry LIKE(?)',"%/%").where.not(ancestry: nil)

    @items = Item.d_search(params[:keyword])

    @keyword = params[:keyword]
    # orderメソッドへ代入する値を条件分岐
    # params[:sort].nil? ? sort  = "created_at DESC" : sort = params[:sort]をリファクタリング
    sort = params[:sort] || "created_at DESC"
    # 入力された値をLIKE句により各カラムと一致したものを抽出する。
    @items = Item.where('name LIKE(?) OR description LIKE(?)', "%#{@keyword}%", "%#{@keyword}%").order(sort)
    @count = @items.count
    # 検索結果が"0"だった場合、全ての商品を表示させる
    if @count == 0
      @items = Item.order(sort)
    end
    @items = @items.page(params[:page]).per(8)

  end

  def detail_search_result
    sort = params[:sort] || "created_at DESC"
    @search_item = Item.ransack(params[:q])
    @items = @search_item.result.page(params[:page]).order(sort)
    @grandchild_category = Category.where('ancestry LIKE(?)',"%/%")
    @child_category = Category.where.not('ancestry LIKE(?)',"%/%").where.not(ancestry: nil)

    @search = params[:q]
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def ensure_correct_user
    if @current_user.id != @item.seller.user.id
      flash[:notice] = "権限がありません"
      redirect_to item_path (@item.id)
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :price, :condition, :parent_category_id, :child_category_id, :category_id, :shipping_id, images_attributes: [:image, :_destroy, :id], shipping_attributes: [:shipping_day, :shipping_fee, :shippingway_id, :shippingarea_id], brands_attributes: [:name, :_destroy, :id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_ransack
    @q = Item.ransack(params[:q])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_detail_search_function.html.haml
.container
  .contents
    = search_form_for(@q,url: detail_search_result_items_path) do |f|
      .detail_search
        .detail_search__group
          .detail_search__group--label
            = fa_icon "search"
            %span キーワードを追加する
          = f.search_field :name_cont, placeholder: "例）値下げ"
        .detail_search__group
          .detail_search__group--label
            = fa_icon "search"
            %span カテゴリーを検索する
        .category-section__pulldown
          .category-select
            = f.collection_select :parent_category_id_in, Category.where(ancestry: nil), :id, :name, { prompt: "選択してください" } ,{class: 'category-select-wrapper__box--select', id: 'parent_category_q'}
            %svg.category-svg{"aria-hidden": "true", fill: "888888", "fill-rule": "evenodd", height: "24", view: "0 0 24 24", width: "24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}

        .detail_search__group
          .detail_search__group--label
            = fa_icon "search"
            %span ブランドを検索する
          = f.search_field :brand_name_cont, placeholder: "例）ナイキ"
        .detail_search__group
          .detail_search__group--label
            = fa_icon "search"
            %span 価格
          .detail_search__group--forms
            = f.search_field :price_gteq, placeholder: "¥ Min", class: "select-half"
            %p 〜
            = f.search_field :price_lteq, placeholder: "¥ Max", class: "select-half"
        .detail_search__group-middle
          .detail_search__group-middle--label
            = fa_icon "search"
            %span 商品の状態
          .detail_search__group-middle--checkbox
            %label
              %input{type: "checkbox"}
              = 'すべて'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '0', nil
              = '未使用に近い'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '1', nil
              = '目立った傷や汚れなし'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '2', nil
              = '送料込み(出品者負担)'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '3', nil
              = 'やや傷や汚れあり'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '4', nil
              = '傷や汚れあり'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :condition_in, {multiple: true, class: "detail_condition detail_checkbox"}, '5', nil
              = '全体的に状態が悪い'

        .detail_search__group-middle
          .detail_search__group-middle--label
            = fa_icon "search"
            %span 配送料の負担
          .detail_search__group-middle--checkbox
            %label
              %input{type: "checkbox"}
              = 'すべて'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :shipping_shipping_fee_in, {multiple: true, class: "detail_condition detail_checkbox"}, '送料込み（出品者負担）', nil
              = '送料込み（出品者負担）'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :shipping_shipping_fee_in, {multiple: true, class: "detail_condition detail_checkbox"}, '着払い（購入者負担）', nil
              = '着払い（購入者負担）'

        .detail_search__group-middle
          .detail_search__group-middle--label
            = fa_icon "search"
            %span 販売状況
          .detail_search__group-middle--checkbox
            %label
              %input{type: "checkbox"}
              = 'すべて'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :selling_status_status_in, {multiple: true, class: "detail_condition detail_checkbox"}, '出品中', nil
              = '出品中'
          .detail_search__group-middle--checkbox
            %label
              = f.check_box :selling_status_status_in, {multiple: true, class: "detail_condition detail_checkbox"}, '売却済み', nil
              = '売却済み'

        .detail_search__btns
          .detail_search__btn--grey
            = link_to "クリア", "",type: "button"
          = f.submit "完了"

app/views/items/_form.html.haml
#previews
  - if @item.persisted?
    - @item.images.each_with_index do |image, i|
      = image_tag image.image.url, data: { index: i }, width: "100", height: '100'

app/views/items/_mainContents.html.haml
%section.introdcution
  .intContent
    .intTitle
      %br/
      人生を変えるフリマアプリ
    %p.intText
      FURIMAはだれでもかんたんに出品・購入できる
      %br/
      フリマアプリです
    .intApp
      = link_to "https://www.apple.com/ios/app-store/" do
        =image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", width: "141.5", height: "41.92", class: 'app-a-icon'
      = link_to "http://play.google.com/store/#?pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", width: "141.5", height: "41.92", class: 'app-g-icon'

%section.reason
  %h2.reasonTitle
    FURIMAが選ばれる3つの理由
  %ul.examples
    %li.example
      .example__image
        %span.number
          1
        =image_tag "http://furima.tokyo/assets/pict-reason-01-77b860b45f32923029756050dafc0f6df01a36675414b0f26f127c64a53baaea.jpg", width: "306", height: "306", class: 'sample-image'
      %h3.example__text
        %span 3分
        ですぐに出品
      %p.example__description
        スマホで入力するだけで簡単出品できる！
    %li.example
      .example__image
        %span.number
          2
        =image_tag "http://furima.tokyo/assets/pict-reason-02-3471b96ea7b52654510992e57dc05af07926de0836200059b7fa4ead05ee4d56.jpg", width: "306", height: "306", class: 'sample-image'
      %h3.example__text
        %span シンプル
        で使いやすい
      %p.example__description
        めんどくさい入力は必要なく、検索も購入もスムーズ！
    %li.example
      .example__image
        %span.number
          3
        =image_tag "http://furima.tokyo/assets/pict-reason-03-1e3c743f3ba3db8c43987d2e257916a615aa8fc59c02bbc116f041a5580ec28f.jpg", width: "306", height: "306", class: 'sample-image'
      %h3.example__text
        手数料
        %span 業界最安
      %p.example__description
        最大3％でお得に出品＆購入！

%section.point
  .pointContent
    .pointTitle
      %br/
      会員数日本一位
    %p.pointText
      FURIMAは、フリマアプリで最も人気。
      %br/
      出品・購入回数も業界最多です！
      %br/
      ほしかったあの商品に出会えるかもしれません。
    .pointApp
      = link_to "https://www.apple.com/ios/app-store/" do
        =image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", width: "141.5", height: "41.92", class: 'app-a-icon'
      = link_to "http://play.google.com/store/#?pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", width: "141.5", height: "41.92", class: 'app-g-icon'

%section.mainfeatures
  %h2.featureTitle
    FURIMAの特徴
  .features
    %section.feature
      .feature__image
        =image_tag "http://furima.tokyo/assets/icon-01-7f6abf70ea7deaed9ab5d8b6d5cb796250e3e292b9ecdc559ebe6492c31fdab8.svg", width: "220", height: "338", class: 'feature-images'
      %h3.feature__text
        簡単に売り買いができる
      %p.feature__description
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    %section.feature
      .feature__image
        =image_tag "http://furima.tokyo/assets/icon-03-9c0d78266a316fec7b738dcf5c68dd987afb9655b13fd2cd5d30bcf09e827694.svg", width: "220", height: "338", class: 'feature-images'
      %h3.feature__text
        売上金は即日振込みに対応
      %p.feature__description
        午前９時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
    %section.feature
      .feature__image
        =image_tag "http://furima.tokyo/assets/icon-04-c4052f85cd6e1f62ea8cac8c55277d7fa4bda971d924f8a2afe72eea6558fa85.svg", width: "220", height: "338", class: 'feature-images'
      %h3.feature__text
        様々な支払いに対応
      %p.feature__description
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

%section.pickup
  %h2.header
    ピックアップカテゴリー
    .itemBox
      .itemHeader
        新規投稿商品
      %ul.itemLists
        - @items.last(4).each do |item|
          = link_to item_path(item.id), method: :get, class:"item" do
            %li.itemList__box
              .itemList__box--image
                -# = image_tag item.images.first.image.url, class: "image"
              .itemList__box--body
                .itemList__box--body--name
                  = item.name
                .itemList__box--body--details
                  .ul 
                    .li
                      = "#{item.price} 円"
                    .li
                  .tax
                    （税込）

%section.pickup
  %h2.pickup-header
    ピックアップブランド
    .itemBox
      .itemHeader
        ブランド1
      %ul.itemLists
        - @apple.last(4).each do |item|
          = link_to item_path(item.id), method: :get, class:"item" do
            %li.itemList__box
              .itemList__box--image
                = image_tag item.images.first.image.url, class: "image"
              .itemList__box--body
                .itemList__box--body--name
                  = item.name
                .itemList__box--body--details
                  .ul 
                    .li
                      = "#{item.price} 円"
                    .li
                  .tax
                    （税込）
  %h2.pickup-header
    ピックアップブランド
    .itemBox
      .itemHeader
        ブランド2
      %ul.itemLists
        - @nike.last(4).each do |item|
          = link_to item_path(item.id), method: :get, class:"item" do
            %li.itemList__box
              .itemList__box--image
                = image_tag item.images.first.image.url, class: "image"
              .itemList__box--body
                .itemList__box--body--name
                  = item.name
                .itemList__box--body--details
                  .ul 
                    .li
                      = "#{item.price} 円"
                    .li
                  .tax
                    （税込）
  %h2.pickup-header
    ピックアップブランド
    .itemBox
      .itemHeader
        ブランド3
      %ul.itemLists
        - @louisvuitton.last(4).each do |item|
          = link_to item_path(item.id), method: :get, class:"item" do
            %li.itemList__box
              .itemList__box--image
                = image_tag item.images.first.image.url, class: "image"
              .itemList__box--body
                .itemList__box--body--name
                  = item.name
                .itemList__box--body--details
                  .ul 
                    .li
                      = "#{item.price} 円"
                    .li
                  .tax
                    （税込）

app/views/items/_search_function_top_contents.html.haml
.search-container__header
  %ul.search-container__header--tabs
    %li.l-side.search-tab
      %i.fas.fa-exchange-alt.fa-lg
      %p.label
        並び替え
      %select{name: :sort_order, class: 'sort_order'}
        %option{value: "location.pathname", name: "location.pathname"}
          並び替え
        %option{value: "price_asc"}
          価格の安い順
        %option{value: "price_desc"}
          価格の高い順
        %option{value: "created_at_asc"}
          出品の古い順
        %option{value: "created_at_desc"}
          出品の新しい順
    %li.search-tab.search-tab-2
      %i.fas.fa-search-plus.fa-lg
      = link_to '詳細検索', '#', remote: true, class: "search-action"

app/views/items/create.html.haml
%h1 投稿が完了しました
= link_to 'トップページに戻る', '/items'

app/views/items/detail_search_result.html.haml
.background
  .search-container
    = render "search_function_top_contents"

    - if @search[:name_cont] == ""
      %h2.search-container__header--keyword
        検索結果
    - else
      %h2.search-container__header--keyword
        %span
          #{@search[:name_cont]}
        の検索結果

    %p.search-container__header--number
      #{@items.length}件表示

    .search-container__main
      %ul.search-result
        - @items.each do|item|
          = link_to item_path(item.id), method: :get, class:"item-list" do
            %li.item-list__box
              .item-list__box--image
                = image_tag item.images.first.image.url, class: "image"
              .item-list__box--name
                = item.name
              .item-list__box--price
                = "#{item.price}円"
              .item-list__box--favorite
                %i.far.fa-heart.LikesIcon-fa-heart
                = item.favorites.count
      .display-box
        = render "detail_search_function"
    .search-container__footer
      = paginate(@items)

app/views/items/index.html.haml
%body
  .mainContent
    =render "mainContents"
  

app/views/items/search.html.haml
.background
  .search-container
    = render "search_function_top_contents"

    - if @keyword == ""
      %h2.search-container__header--keyword
        検索結果
    - else
      %h2.search-container__header--keyword
        %span
          #{@keyword}
        の検索結果

    %p.search-container__header--number
      #{@items.length}件表示

    .search-container__main
      %ul.search-result
        - @items.each do|item|
          = link_to item_path(item.id), method: :get, class:"item-list" do
            %li.item-list__box
              .item-list__box--image
                = image_tag item.images.first.image.url, class: "image"
              .item-list__box--name
                = item.name
              .item-list__box--price
                = "#{item.price}円"
              .item-list__box--favorite
                %i.far.fa-heart.LikesIcon-fa-heart
                = item.favorites.count
      .display-box
        = render "detail_search_function"
    .search-container__footer
      = paginate(@items)

app/views/items/show.html.haml
.Main
  .showMain
    .contentBox
      .topContent
        .itemBox
          %h2.itemBox__name
            = @item.name
          .itemBox__body
            .item-main-image
              =image_tag @image.image.url, size: "500x350", class: "main-image"
            %ul
              - @item.images.first(3).each.with_index do |image, index|
                %li
                  = image_tag image.image.url, size: "166x100", class: "sub-image"
          .itemBox__price
            %span
              = "¥#{@item.price}"
            .itemBox__price-detail
              %span
                （税込）
              %span
                = @item.shipping.shipping_fee
          .itemBox_detail
            = @item.description
          .table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    = @item.seller.user.nickname
                %tr
                  %th
                    カテゴリー
                  %td
                    = link_to "#{@category.name}", parents_category_path(@category)
                    %br
                    = link_to "#{@category_child.name}", children_category_path(@category_child)
                    %br
                    = link_to "#{@item.category.name}", grand_children_category_path(@category_grand_child)
                %tr
                  %th
                    ブランド
                  %td
                    - if @item.brand.present?
                      = @item.brand.name 
                %tr
                  %th
                    商品の状態
                  %td
                    = @item.condition
                %tr
                  %th
                    配送料の負担
                  %td
                    = @item.shipping.shipping_fee
                %tr
                  %th
                    発送元の地域
                  %td
                    = @item.shipping.shippingarea.name
                %tr
                  %th
                    発送日の目安
                  %td
                    = @item.shipping.shipping_day
          .optionalArea
            %ul
              - if user_signed_in?
                - if current_user.already_favorited?(@item)     
                  .LikesIcon
                    %i.fas.fa-heart.LikesIcon-fa-heart.heart    
                - else
                  .LikesIcon
                    %i.far.fa-heart.LikesIcon-fa-heart 
              %li.counts
                %p.favorite
                  お気に入り数：
                  = @item.favorites.count
                .favorites-box
                  .favorites_buttons{data: {id: @item.id}}
                    = render partial: 'favorites/favorite', locals: { item: @item}
                  - if user_signed_in?
                    %p
                      = link_to 'お気に入り一覧ページ', user_favorites_users_path, class: "favorites-lists"
            %ul.optional
              %li.optionalBtn
                = link_to '#' do
                  %i.fa.fa-flag
                    不適切な商品の通報

        .itemBox-container
          - if user_signed_in?
            - if user_signed_in? && current_user.id == @item.seller.user.id
              .li-edit
                = link_to '商品の編集', edit_item_path, class: "link-path"
              .li-or
                or
              .li-delete
                = link_to 'この商品を削除する', item_path, method: :delete, class: "link-path"
            - else
              - if @item.buyer.present?
                .li-status
                  売却済
              - else
                .li-purchase
                  = link_to 'この商品を購入する', item_purchase_path(@item.id), class: "link-path"

        .item-detail-message 
          .message-container
            .message-content
              %ul.message-items
                - if @comments
                  - @comments.each do |comment|
                    %li.clearfix
                      = link_to comment.user, class: "message-user" do
                        .figure
                          .div
                            = image_tag "https://static.mercdn.net/thumb/members/551390331.jpg?1581956265", width: 40, height: 40
                          %figcaption.bold
                            = comment.user.nickname
                        .message-is-seller
                          出品者
                      .message-body
                        .message-body-text
                          = comment.comment
                        .message-icons.clearfix
                          %time.message-icon-left
                            %i.icon-time
                            %time(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at) + '前'
                          .message-icon-right
                            = link_to '#' do
                              %i.fa.fa-flag
                        %i.icon-balloon
                        
            - if current_user
              = form_with( model: [@item, @comment], class: "new_comment", id: "comment", remote: true) do |f|
                = f.text_area :comment, placeholder: "コメントする", rows: "2", class: "comment_body", id: "comment_text"
                %p.noticeMsg
                  相手のことを考え丁寧なコメントを心がけましょう。
                  %br
                  不快な言葉遣いなどは利用制限や退去処分となることがあります。
                = f.submit "コメントする", class: "commentBtn", id: "commentBtn" do
                  %i.fa.fa-comment

      %ul.links
        %li.left
          = link_to '＜前の商品', item_path(@previous_item) if @previous_item
        %li.right
          = link_to '後ろの商品＞', item_path(@next_item) if @next_item
      .relatedItems
        = link_to "#{@category.name}をもっと見る", parents_category_path(@category)
        .productLists
          