config/routes.rb
Rails.application.routes.draw do

  # patch '/brand/:id/index', to: 'brand#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end

  root to: "items#index"

  resources :items do

    resources :favorites, only: [:create, :destroy, :index]
    resources :comments, only: [:create]

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    # 編集画面でカテゴリーを編集可能にするための記述
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      get 'search'
      get 'detail_search'
      get 'detail_search_result'
    end

    resources :purchase, only: [:index] do
      member do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get '/brand/:id/index', to: 'brand#index', as: 'brand'

  resources :users, only: :show do

    collection do
      get 'logouts', to: 'logouts#index'
      get 'cards', to: 'cards#index'
      get 'user_favorites', to: 'user_favorites#index'
    end
  end

  resources :category, only: :new do
    member do
      get 'parents', to: 'category#parents'
      get 'children', to: 'category#children'
      get 'grand_children', to: 'category#grand_children'
    end
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Payment.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( #同時に顧客IDもpayjpサーバーで生成される
      card: params['payjp-token'], #jsで受け取ったpayjp_tokenの情報をpeyjpのサーバーで保存
      )
      @card = Payment.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      #@cardインスタンス変数にpaymentsテーブルの各カラムに入れたい情報を代入
      if @card.save
        redirect_to controller: :cards, action: "index"
      else
        redirect_to action: "new"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Payment.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id) #payjpサーバー上からカードの顧客IDで顧客を検索
      customer.delete #payjpサーバーのデータ削除
      card.delete #DBのデータ削除
    end
      redirect_to controller: :cards, action: "index"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Payment.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand
      @card_month = @default_card_information.exp_month
      @card_year = @default_card_information.exp_year % 1000
      case @card_brand
      when "Visa" then
        @card_image = "cc-visa fa-2x"
      when "MasterCard" then
        @card_image = "cc-mastercard fa-2x"
      when "JCB" then
        @card_image = "cc-jcb fa-2x"
      when "American Express" then
        @card_image = "cc-amex fa-2x"
      when "Diners Club" then
        @card_image = "cc-diners-club fa-2x"
      when "Discover" then
        @card_image = "cc-discover fa-2x"
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    card = Payment.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand
      @card_month = @default_card_information.exp_month
      @card_year = @default_card_information.exp_year % 1000
      case @card_brand
      when "Visa" then
        @card_image = "cc-visa fa-2x"
      when "MasterCard" then
        @card_image = "cc-mastercard fa-2x"
      when "JCB" then
        @card_image = "cc-jcb fa-2x"
      when "American Express" then
        @card_image = "cc-amex fa-2x"
      when "Diners Club" then
        @card_image = "cc-diners-club fa-2x"
      when "Discover" then
        @card_image = "cc-discover fa-2x"
      end
    end
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/card/_card-footer.html.haml
.mypage-card-contents__footer
  .mypage-card-contents__footer__body
    .policy
      %ul.policy-list
        %li.policy-list__item
          %a.name
            = link_to "#" do
              プライバシーポリシー
        %li.policy-list__item
          %a.name
            = link_to "#" do
              フリマ利用規約
        %li.policy-list__item
          %a.name
            = link_to "#" do
              特定商取引に関する表記
    %a.logo
      = link_to root_path do
        %svg{fill: "none", height: "62", viewbox: "0 0 214 62", width: "214", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M85.3299 30.56C85.841 30.5626 86.3304 30.7668 86.6917 31.1282C87.0531 31.4896 87.2573 31.979 87.2599 32.49C87.2626 32.7442 87.2145 32.9964 87.1185 33.2318C87.0224 33.4671 86.8804 33.6809 86.7006 33.8607C86.5209 34.0405 86.307 34.1825 86.0717 34.2786C85.8363 34.3746 85.5841 34.4227 85.3299 34.42H76.6699V43.58C76.6699 44.1105 76.4592 44.6192 76.0841 44.9942C75.7091 45.3693 75.2004 45.58 74.6699 45.58C74.1395 45.58 73.6308 45.3693 73.2557 44.9942C72.8806 44.6192 72.6699 44.1105 72.6699 43.58V18.77C72.6699 17.9744 72.986 17.2113 73.5486 16.6487C74.1112 16.0861 74.8743 15.77 75.6699 15.77H85.6699C86.1765 15.77 86.6623 15.9713 87.0205 16.3294C87.3787 16.6876 87.5799 17.1735 87.5799 17.68C87.5799 18.1866 87.3787 18.6724 87.0205 19.0306C86.6623 19.3888 86.1765 19.59 85.6699 19.59H76.6699V30.56H85.3299Z", fill: "#231815"}
          %path{d: "M113.48 36.8901C113.548 38.0254 113.383 39.1626 112.996 40.2319C112.608 41.3011 112.006 42.2798 111.226 43.1078C110.447 43.9358 109.506 44.5955 108.462 45.0465C107.418 45.4974 106.292 45.73 105.155 45.73C104.018 45.73 102.892 45.4974 101.848 45.0465C100.804 44.5955 99.8632 43.9358 99.0835 43.1078C98.3037 42.2798 97.7016 41.3011 97.314 40.2319C96.9265 39.1626 96.7618 38.0254 96.8299 36.8901V18.4001C96.8111 18.141 96.8458 17.8808 96.932 17.6357C97.0181 17.3907 97.1539 17.166 97.3308 16.9757C97.5077 16.7855 97.7219 16.6338 97.96 16.53C98.1982 16.4262 98.4552 16.3727 98.7149 16.3727C98.9747 16.3727 99.2317 16.4262 99.4699 16.53C99.708 16.6338 99.9222 16.7855 100.099 16.9757C100.276 17.166 100.412 17.3907 100.498 17.6357C100.584 17.8808 100.619 18.141 100.6 18.4001V36.8901C100.533 37.5256 100.601 38.1681 100.798 38.7759C100.996 39.3837 101.319 39.9432 101.746 40.4181C102.174 40.893 102.696 41.2727 103.28 41.5327C103.864 41.7926 104.496 41.9269 105.135 41.9269C105.774 41.9269 106.406 41.7926 106.99 41.5327C107.573 41.2727 108.096 40.893 108.524 40.4181C108.951 39.9432 109.274 39.3837 109.472 38.7759C109.669 38.1681 109.737 37.5256 109.67 36.8901V18.4001C109.705 17.9187 109.921 17.4683 110.274 17.1396C110.628 16.8109 111.092 16.6282 111.575 16.6282C112.058 16.6282 112.522 16.8109 112.876 17.1396C113.229 17.4683 113.445 17.9187 113.48 18.4001V36.8901Z", fill: "#231815"}
          %path{d: "M139.25 30.78C139.239 32.8998 138.399 34.9311 136.91 36.44C136.74 36.6295 136.545 36.7944 136.33 36.93L138.58 43.17C138.675 43.4118 138.72 43.6703 138.712 43.9299C138.704 44.1895 138.644 44.4449 138.534 44.6804C138.425 44.916 138.269 45.127 138.076 45.3005C137.882 45.474 137.656 45.6065 137.41 45.69C136.92 45.8595 136.384 45.8323 135.914 45.614C135.444 45.3958 135.077 45.0036 134.89 44.52L132.74 38.64C132.252 38.7297 131.756 38.7732 131.26 38.77H127.89V43.77C127.89 44.2885 127.689 44.7869 127.329 45.1601C126.969 45.5332 126.478 45.7519 125.96 45.77C125.43 45.77 124.921 45.5593 124.546 45.1842C124.171 44.8092 123.96 44.3005 123.96 43.77V18.77C123.96 17.9744 124.276 17.2113 124.839 16.6487C125.401 16.0861 126.164 15.77 126.96 15.77H131.23C132.28 15.7616 133.322 15.9644 134.293 16.3664C135.263 16.7684 136.143 17.3613 136.88 18.11C138.366 19.6165 139.206 21.6437 139.22 23.76L139.25 30.78ZM127.89 34.91H131.26C132.347 34.8969 133.384 34.4559 134.148 33.6828C134.912 32.9097 135.34 31.8668 135.34 30.78V23.78C135.337 22.695 134.908 21.6546 134.145 20.8837C133.381 20.1127 132.345 19.6732 131.26 19.66H127.89V34.91Z", fill: "#231815"}
          %path{d: "M153.52 43.67C153.52 44.2004 153.309 44.7091 152.934 45.0842C152.559 45.4593 152.05 45.67 151.52 45.67C150.99 45.67 150.481 45.4593 150.106 45.0842C149.731 44.7091 149.52 44.2004 149.52 43.67V17.6C149.52 17.0695 149.731 16.5608 150.106 16.1858C150.481 15.8107 150.99 15.6 151.52 15.6C152.05 15.6 152.559 15.8107 152.934 16.1858C153.309 16.5608 153.52 17.0695 153.52 17.6V43.67Z", fill: "#231815"}
          %path{d: "M183.59 14.64C183.844 14.6387 184.095 14.6877 184.33 14.7843C184.565 14.8808 184.778 15.0229 184.958 15.2024C185.137 15.3819 185.279 15.5951 185.376 15.8299C185.472 16.0647 185.521 16.3162 185.52 16.57V43.76C185.539 44.0218 185.504 44.2847 185.417 44.5323C185.33 44.7798 185.192 45.0068 185.014 45.199C184.835 45.3912 184.618 45.5444 184.378 45.6493C184.137 45.7541 183.877 45.8082 183.615 45.8082C183.353 45.8082 183.093 45.7541 182.852 45.6493C182.612 45.5444 182.395 45.3912 182.216 45.199C182.038 45.0068 181.9 44.7798 181.813 44.5323C181.726 44.2847 181.691 44.0218 181.71 43.76V25.31L177.22 41.56C177.105 41.9837 176.853 42.3577 176.505 42.6244C176.156 42.8911 175.729 43.0355 175.29 43.0355C174.851 43.0355 174.424 42.8911 174.075 42.6244C173.726 42.3577 173.475 41.9837 173.36 41.56L169 25.49V43.76C169 44.0109 168.951 44.2592 168.855 44.491C168.759 44.7227 168.618 44.9333 168.441 45.1106C168.263 45.288 168.053 45.4287 167.821 45.5247C167.589 45.6206 167.341 45.67 167.09 45.67C166.839 45.67 166.591 45.6206 166.359 45.5247C166.127 45.4287 165.917 45.288 165.739 45.1106C165.562 44.9333 165.421 44.7227 165.325 44.491C165.229 44.2592 165.18 44.0109 165.18 43.76V16.57C165.179 16.3162 165.228 16.0647 165.324 15.8299C165.421 15.5951 165.563 15.3819 165.742 15.2024C165.922 15.0229 166.135 14.8808 166.37 14.7843C166.605 14.6877 166.856 14.6387 167.11 14.64C167.656 14.6407 168.186 14.8229 168.617 15.1578C169.047 15.4927 169.355 15.9614 169.49 16.49L175.37 34.91L181.21 16.49C181.357 15.968 181.668 15.5067 182.096 15.1738C182.524 14.8409 183.048 14.6539 183.59 14.64Z", fill: "#231815"}
          %path{d: "M213.37 43.53C213.439 43.7762 213.459 44.0339 213.427 44.2877C213.396 44.5416 213.314 44.7866 213.186 45.0083C213.058 45.23 212.888 45.424 212.684 45.5789C212.48 45.7337 212.248 45.8463 212 45.91C211.507 46.0299 210.988 45.9583 210.546 45.7095C210.104 45.4608 209.773 45.0534 209.62 44.57L208.23 39.45H198.07L196.67 44.52C196.519 45.0032 196.191 45.4111 195.751 45.6617C195.311 45.9122 194.793 45.9866 194.3 45.87C193.82 45.7282 193.415 45.4035 193.172 44.9658C192.928 44.5282 192.867 44.0126 193 43.53L201.17 16.35C201.3 15.9209 201.565 15.5451 201.925 15.278C202.285 15.0109 202.722 14.8667 203.17 14.8667C203.618 14.8667 204.055 15.0109 204.415 15.278C204.775 15.5451 205.04 15.9209 205.17 16.35L213.37 43.53ZM199.1 35.63H207.18L203.18 23.63L199.1 35.63Z", fill: "#231815"}
          %path{d: "M27.3901 61.14C26.9197 61.1388 26.4577 61.0147 26.0501 60.78L1.91006 46.84C1.49945 46.6053 1.15827 46.2661 0.921167 45.8569C0.684061 45.4477 0.559477 44.983 0.560061 44.51V16.63C0.559477 16.1571 0.684061 15.6924 0.921167 15.2832C1.15827 14.8739 1.49945 14.5347 1.91006 14.3L26.0501 0.360025C26.459 0.123929 26.9229 -0.000366211 27.3951 -0.000366211C27.8672 -0.000366211 28.3311 0.123929 28.7401 0.360025L52.8801 14.3C53.2907 14.5347 53.6318 14.8739 53.8689 15.2832C54.1061 15.6924 54.2306 16.1571 54.2301 16.63V44.51C54.2306 44.983 54.1061 45.4477 53.8689 45.8569C53.6318 46.2661 53.2907 46.6053 52.8801 46.84L28.7401 60.78C28.3294 61.0164 27.8639 61.1405 27.3901 61.14ZM5.94006 43L27.3901 55.34L48.8501 43V18.18L27.3901 5.80002L5.94006 18.18V43Z", fill: "#3ECACF"}
          %path{d: "M27.39 33.26C26.9197 33.2579 26.458 33.1338 26.05 32.9L1.90996 19C1.32203 18.6298 0.900141 18.0464 0.732655 17.3721C0.56517 16.6979 0.665077 15.9849 1.01146 15.3826C1.35784 14.7803 1.92382 14.3354 2.59087 14.1411C3.25792 13.9467 3.97429 14.018 4.58996 14.34L28.74 28.24C29.2436 28.5405 29.6353 28.9973 29.8553 29.5409C30.0753 30.0845 30.1117 30.6852 29.9588 31.2513C29.8059 31.8175 29.4722 32.3182 29.0085 32.6772C28.5447 33.0362 27.9764 33.2339 27.39 33.24V33.26Z", fill: "#3ECACF"}
          %path{d: "M27.4001 33.2601C26.8137 33.2539 26.2453 33.0563 25.7816 32.6973C25.3179 32.3383 24.9841 31.8376 24.8313 31.2714C24.6784 30.7052 24.7148 30.1046 24.9348 29.561C25.1548 29.0173 25.5465 28.5605 26.0501 28.2601L50.1901 14.3001C50.4987 14.1234 50.8391 14.0093 51.1918 13.9642C51.5445 13.9192 51.9027 13.944 52.2458 14.0373C52.5889 14.1306 52.9102 14.2906 53.1915 14.5081C53.4728 14.7257 53.7085 14.9965 53.8851 15.3051C54.0618 15.6137 54.1759 15.954 54.2209 16.3067C54.266 16.6595 54.2412 17.0176 54.1479 17.3607C54.0546 17.7038 53.8946 18.0252 53.677 18.3065C53.4595 18.5878 53.1887 18.8234 52.8801 19.0001L28.7401 32.9001C28.3321 33.1339 27.8704 33.2579 27.4001 33.2601Z", fill: "#3ECACF"}
          %path{d: "M27.39 61.14C26.6773 61.1374 25.9946 60.8531 25.4907 60.3492C24.9868 59.8453 24.7026 59.1626 24.7 58.45V30.57C24.7 29.8566 24.9834 29.1724 25.4878 28.6679C25.9923 28.1634 26.6765 27.88 27.39 27.88C28.1034 27.88 28.7876 28.1634 29.2921 28.6679C29.7965 29.1724 30.08 29.8566 30.08 30.57V58.45C30.08 59.1634 29.7965 59.8477 29.2921 60.3521C28.7876 60.8566 28.1034 61.14 27.39 61.14V61.14Z", fill: "#3ECACF"}
          %path{d: "M27.6 44.5501C27.017 44.5355 26.4544 44.3319 25.9972 43.9698C25.5399 43.6078 25.2127 43.1069 25.0649 42.5427C24.9171 41.9785 24.9566 41.3815 25.1776 40.8417C25.3986 40.302 25.789 39.8486 26.29 39.5501L50.23 26.1701C50.8533 25.8226 51.5891 25.737 52.2754 25.932C52.9618 26.1271 53.5426 26.5868 53.89 27.2101C54.2375 27.8333 54.3231 28.5691 54.1281 29.2555C53.933 29.9418 53.4733 30.5226 52.85 30.8701L28.9101 44.2101C28.509 44.432 28.0584 44.5489 27.6 44.5501V44.5501Z", fill: "#3ECACF"}
    %p.company ©︎FURIMA, Inc.

app/views/card/new.html.haml
- breadcrumb :card

.card-registration-contents
  = render 'card-header'
  .card-registration__main
    .card-registration__main__container
      .card-registration__main__container__head
        %h2 クレジットカード情報入力
      .card-registration__main__container__form
        = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .card-form__content
            .card-form__content__group
              %label カード番号
              %span.form-require 必須
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %br
              %ul
                %li
                  = icon("fab", "cc-visa fa-2x")
                %li
                  = icon("fab", "cc-mastercard fa-2x")
                %li
                  = icon("fab", "cc-jcb fa-2x")
                %li
                  = icon("fab", "cc-amex fa-2x")
                %li
                  = icon("fab", "cc-diners-club fa-2x")
                %li
                  = icon("fab", "cc-discover fa-2x")
            .card-form__content__group
              %label 有効期限
              %span.form-require 必須
              %br
              .card-form__content__group__exp
                .card-form__content__group__exp__half
                  %select#exp_month{name: "exp_month", type: "text", class: "number-half"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %svg.card-svg{"aria-hidden": "true", fill: "888888", "fill-rule": "evenodd", height: "24", viewbox: "0 0 24 24", width: "24"}
                    %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
                  %span.number-half__logo 月
                .card-form__content__group__exp__half
                  %select#exp_year{name: "exp_year", type: "text", class: "number-half"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %svg.card-svg{"aria-hidden": "true", fill: "888888", "fill-rule": "evenodd", height: "24", viewbox: "0 0 24 24", width: "24"}
                    %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
                  %span.number-half__logo 年
                  %br
            .card-form__content__group
              %label セキュリティコード
              %span.form-require 必須
              = text_field_tag "cvc", "", class: "number", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .card-help
                = icon("far", "question-circle")
                %span
                  = link_to "カードの裏面の番号とは？", "#"
            .card-form__content__group
              #card_token
              = submit_tag "追加する", id: "token_submit", class: "registration-btn"
  = render 'card-footer'

app/views/card/show.html.haml
.mypage-card-contents
  = render 'card-header'
  .user-card
    .user-card__head
      %h2 支払い方法
    .user-card__main
      .card-list
        .card-list__head
          %h3.card-list__head__logo
            クレジットカード一覧
        .card-list__main
          - if @default_card_information.present?
            .card-list__main__info
              .card-list__main__info__brand
                = icon("fab", "#{@card_image}")
              .card-list__main__info__num
                = "************" + @default_card_information.last4
              .card-list__main__info__num
                = "#{@card_month}" + " / " + "#{@card_year}"
              .card-list__main__info__delete
                = link_to '削除する', delete_card_index_path, method: :post, class: "card-list__main__info__delete__btn"
          - else
            .card-list__main__new
              = link_to new_card_path, class: "card-list__main__new__btn" do
                %i.fas.fa-credit-card
                クレジットカードを追加する
      .user-card__main__card-help
        %span 支払い方法について
        %i.fas.fa-chevron-right         
  = render 'card-footer'

  