config/routes.rb
Rails.application.routes.draw do

  # patch '/brand/:id/index', to: 'brand#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end

  root to: "items#index"

  resources :items do

    resources :favorites, only: [:create, :destroy, :index]
    resources :comments, only: [:create]

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    # 編集画面でカテゴリーを編集可能にするための記述
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      get 'search'
      get 'detail_search'
      get 'detail_search_result'
    end

    resources :purchase, only: [:index] do
      member do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get '/brand/:id/index', to: 'brand#index', as: 'brand'

  resources :users, only: :show do

    collection do
      get 'logouts', to: 'logouts#index'
      get 'cards', to: 'cards#index'
      get 'user_favorites', to: 'user_favorites#index'
    end
  end

  resources :category, only: :new do
    member do
      get 'parents', to: 'category#parents'
      get 'children', to: 'category#children'
      get 'grand_children', to: 'category#grand_children'
    end
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Payment.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( #同時に顧客IDもpayjpサーバーで生成される
      card: params['payjp-token'], #jsで受け取ったpayjp_tokenの情報をpeyjpのサーバーで保存
      )
      @card = Payment.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      #@cardインスタンス変数にpaymentsテーブルの各カラムに入れたい情報を代入
      if @card.save
        redirect_to controller: :cards, action: "index"
      else
        redirect_to action: "new"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Payment.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id) #payjpサーバー上からカードの顧客IDで顧客を検索
      customer.delete #payjpサーバーのデータ削除
      card.delete #DBのデータ削除
    end
      redirect_to controller: :cards, action: "index"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Payment.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand
      @card_month = @default_card_information.exp_month
      @card_year = @default_card_information.exp_year % 1000
      case @card_brand
      when "Visa" then
        @card_image = "cc-visa fa-2x"
      when "MasterCard" then
        @card_image = "cc-mastercard fa-2x"
      when "JCB" then
        @card_image = "cc-jcb fa-2x"
      when "American Express" then
        @card_image = "cc-amex fa-2x"
      when "Diners Club" then
        @card_image = "cc-diners-club fa-2x"
      when "Discover" then
        @card_image = "cc-discover fa-2x"
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    card = Payment.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand
      @card_month = @default_card_information.exp_month
      @card_year = @default_card_information.exp_year % 1000
      case @card_brand
      when "Visa" then
        @card_image = "cc-visa fa-2x"
      when "MasterCard" then
        @card_image = "cc-mastercard fa-2x"
      when "JCB" then
        @card_image = "cc-jcb fa-2x"
      when "American Express" then
        @card_image = "cc-amex fa-2x"
      when "Diners Club" then
        @card_image = "cc-diners-club fa-2x"
      when "Discover" then
        @card_image = "cc-discover fa-2x"
      end
    end
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards_left_box.html.haml
.user-mypage
  %ul.user-mypage__container
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "マイページ", user_path(current_user.id), class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "お知らせ", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "やることリスト", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "いいね！一覧", user_favorites_users_path, class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "出品する", new_item_path, class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "下書き一覧", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "出品した商品 - 出品中", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "出品した商品 - 取引中", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "出品した商品 - 売却済み", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "購入した商品 - 取引中", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "購入した商品 - 過去の取引", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "ニュース一覧", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "評価一覧", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "ガイド", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "お問い合わせ", "#", class: "content"
  %ul.user-mypage__container.add-margin-top
    %p
      フリペイ
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "売上・振込申請", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "ポイント", "#", class: "content"
  %ul.user-mypage__container.add-margin-top
    %p
      設定
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "プロフィール", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "発送元・お届け先住所変更", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right.addcolor
      = link_to "支払い方法", cards_users_path, class: "content addcolor"

    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "メール/パスワード", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "本人情報", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "電話番号の確認", "#", class: "content"
    %li
      .icon-arrow
        %i.fas.fa-chevron-right.icon-arrow__right
      = link_to "ログアウト", logouts_users_path, class: "content"

app/views/cards/index.html.haml
- breadcrumb :mypage

.background-mypage
  .flex-box
    .left-box
      =render "cards_left_box"
    .right-box
      .user-mypage
        .mypage-card-contents
          .user-card
            .user-card__head
              %h2 支払い方法
            .user-card__main
              .card-list
                .card-list__head
                  %h3.card-list__head__logo
                    クレジットカード一覧
                .card-list__main
                  - if @default_card_information.present?
                    .card-list__main__info
                      .card-list__main__info__brand
                        = icon("fab", "#{@card_image}")
                      .card-list__main__info__num
                        = "************" + @default_card_information.last4
                      .card-list__main__info__num
                        = "#{@card_month}" + " / " + "#{@card_year}"
                      .card-list__main__info__delete
                        = link_to '削除する', delete_card_index_path, method: :post, class: "card-list__main__info__delete__btn"
                  - else
                    .card-list__main__new
                      = link_to new_card_path, class: "card-list__main__new__btn" do
                        %i.fas.fa-credit-card
                        クレジットカードを追加する
              .user-card__main__card-help
                %span 支払い方法について
                %i.fas.fa-chevron-right